### ISSUE TITLE
No Data Placeholder

### ISSUE THREAD

**Issue by rhettl** [uci-soe/notice-board-gcalendar#2]
Hey, 

While working on my code I see this: 
![image](https://user-images.githubusercontent.com/1766765/64889177-998e1080-d621-11e9-91f7-810be75dce59.png)

This is working as expected, but it looks like it isn't because there isn't any content. This brings me to my next feature request:

### Can you add a "No Data"/Empty placeholder.

Basically, this is a child which is only used when there are no children. 

There should be a default one. It should basically be empty except for maybe a CSS content tag. This empty placeholder shows that the code is working as expected and that there is just nothing happening today. 

There should also be the option to use one's own custom no-content. This is mostly for when someone wants to add a lot more structure. so if they want a photo of a sad puppy or a longer description to explain why there might be no content. in cases like this the custom override (passed in through a property) would take preciseness. 

 the code would be something like 

```css
.calendar > .no-content {
  content: "There is no content here."
}
```

```jsx

function CalendarNoEvent () {
  return (<div className="no-content" />);
}


function Calendar () {

  // if parent declared child
  const Event = props.children || CalendarEvent;

  // if Parent declared an empty child
  const NoEvent = props.noEvent || CalendarNoEvent;

  // Check if there are events to display and show the events or show the no-event
  return (
    <div className="calendar">

      {events.length 
          ? events.map(e => CalendarEvent(e))
          : NoEvent()
      }

    </div>
  );
}

function CustomNoEvent () {
  return (
    <div className="empty-event">
      <h2>No events today</h2>
      <p>Nothing to see here, move along. Check back in tomorrow.</p>
    </div>
  );
}
function App () {
  return (
    <Calendar noEvent={CustomNoEvent} />
  );
}
```

Please add this to both student and tech schedules. Thank you!

**Comment by masonn3** [comment]
Added changes for No Data Placeholder in commit 806b50f642bae8f23a17838f4ad9a0aeed180667.
